### ISSUE TITLE
Index was out of range

### ISSUE THREAD

**Issue by kvasnyj** [Nauplius/FoundationSync#1]
Hello,
Issue with timer job.

Timer status: failed.
Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

Sharepoint 2013;

**Comment by andy68man** [comment]
Hello,

I'm getting this as well. Just using NTLM authentication with Sharepoint 2013.

Log file error is below, any ideas of what to try...?

Thanks,

Andy

01/21/2015 11:03:01.34 	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Database                      	4ohq	Medium  	Site Enumeration Stack:    at Microsoft.SharePoint.SPBaseCollection.GetEnumerator()     at Nauplius.SP.UserSync.AttributePush.Execute(Guid targetInstanceId)     at Microsoft.SharePoint.Administration.SPTimerJobInvokeInternal.Invoke(SPJobDefinition jd, Guid targetInstanceId, Boolean isTimerService, Int32& result)     at Microsoft.SharePoint.Administration.SPTimerJobInvoke.Invoke(TimerJobExecuteData& data, Int32& result)  	5be5e19c-30be-00e8-2382-7f82edba3471
01/21/2015 11:03:01.50 	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Monitoring                    	b4ly	High    	Leaving Monitored Scope (EnsureListItemsData). Execution Time=128.407032178671	5be5e19c-30be-00e8-2382-7f82edba3471
01/21/2015 11:03:01.51 	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Timer                         	6398	Critical	The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 13d47ca1-4b11-4dfc-9a0f-3d3069c08d1d) threw an exception. More information is included below.  Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index	5be5e19c-30be-00e8-2382-7f82edba3471
01/21/2015 11:03:01.51 	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Timer                         	72ae	Unexpected	Exception stack trace:    at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)     at Nauplius.SP.UserSync.AttributePush.GetThumbnail(SPUser user, DirectoryEntry directoryEntry)     at Nauplius.SP.UserSync.AttributePush.UpdateUilUser(SPUser user, DirectoryEntry directoryEntry, SPListItemCollection listItems, Int32 itemCount)     at Nauplius.SP.UserSync.AttributePush.SearchPrincipals(SPPeoplePickerSearchActiveDirectoryDomain domain, HashSet`1 objPrincipals, SPWebApplication webApplication, SPSite site, Boolean isGroup)     at Nauplius.SP.UserSync.AttributePush.GetDomains(HashSet`1 objPrincipals, SPWebApplication webApplication, SPSite site, Boolean isGroup)     at Nauplius.SP.UserSync.AttributePush.Execute(Guid targetInstanceId)     at Microsoft.SharePoint.Adm...	5be5e19c-30be-00e8-2382-7f82edba3471
01/21/2015 11:03:01.51*	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Timer                         	72ae	Unexpected	...inistration.SPTimerJobInvokeInternal.Invoke(SPJobDefinition jd, Guid targetInstanceId, Boolean isTimerService, Int32& result)	5be5e19c-30be-00e8-2382-7f82edba3471
01/21/2015 11:03:01.53 	OWSTIMER.EXE (0x0A08)                   	0x0A44	SharePoint Foundation         	Monitoring                    	b4ly	Medium  	Leaving Monitored Scope (Timer Job Nauplius.SharePoint.FoundationSync). Execution Time=185.223820345882	5be5e19c-30be-00e8-2382-7f82edba3471

**Comment by tseward** [comment]
I've published a beta release to hopefully capture this particular issue. Try it out and let me know how it goes. https://github.com/Nauplius/FoundationSync/releases/tag/2.51B

**Comment by STL1te** [comment]
Error in this line:
``` 
var byteArray = (byte[])directoryEntry.Properties["thumbnailPhoto"][0];
```
I fix it this way:
```
byte[] byteArray = null;
try {
    byteArray = (byte[])directoryEntry.Properties["thumbnailPhoto"][0];
} catch {
}          
if( byteArray != null ) {
    ...
}
```

**Comment by tseward** [comment]
I changed it to this:

            else
            {
                try
                {
                    var byteArray = (byte[])directoryEntry.Properties["thumbnailPhoto"][0];

                    if (byteArray.Length > 0)
                    {
                        using (var ms = new MemoryStream(byteArray))
                        {
                            var image = new Bitmap(ms);
                            fileUri = SaveImage(user, image, siteUri, fileName);
                        }
                    }
                }
                catch (IndexOutOfRangeException ex)
                {
                    return string.Empty;
                }
            }

            return !string.IsNullOrEmpty(fileUri) ? fileUri : null;

**Comment by sbranly** [comment]
Hi. I know this is marked as closed but I would appreciate some help as I am having issues with this error and in my sharepoint logs I get the following: 05/11/2015 12:55:46.58	OWSTIMER.EXE (0x0604)	0x0608	Nauplius	FoundationSync	2001	Verbose	Error retriving file, continuing to pull new file.	4361059d-4f86-a051-c72e-1fb422661f3c	

My Farm Administrator account is a domain user account, is a contributor to the UserPhotos library (with Everyone having read access) and yet I keep getting this error. Using the latest release.  Thank you

**Comment by tseward** [comment]
What that means is the user's picture could not be retrieved from the specified SharePoint Site, so it moves onto attempting to pull it from Active Directory or Exchange, depending on how you have it configured. You'll notice that it is a Verbose message (and a catch-all).

**Comment by sbranly** [comment]
Hi. I provided what I could see in the log as I'm not able to get the job
to succeed.  I keep getting the index error.  I am not sure where I've gone
wrong in the installation of your project.

I have a Farm account that runs the timer server that is a domain user. It
is not a local admin on the Sharepoint server.

I have Everyone with read access to the Userphoto site collection.

I have the Farm account with contributor access to the Userphoto library in
the site collection.

Before I activated the site feature and added the url to the site
collection the job did succeed.  So I believe there is an issue with
thumbnails but I'm unable to figure it out.

**Comment by tseward** [comment]
Great, thank you that helps. Can you provide what the URL is to your UserPhoto library and what URL you've set in Central Administration -> Application Management -> Configure Profile Sync Settings? Can you also provide the value of "pictureStorageUrl" from:

```powershell
$farm = Get-SPFarm
$farm.Properties
```

**Comment by sbranly** [comment]
Can you provide what the URL is to your UserPhoto library:
http://accushare/sites/users/_layouts/15/start.aspx#/UserPhotos/Forms/Thumbnails.aspx

what URL you've set in Central Administration -> Application Management ->
Configure Profile Sync Settings?
http://accushare/sites/users

Can you also provide the value of "pictureStorageUrl" from:

$farm = Get-SPFarm
$farm.Properties


Name                           Value
----                           -----
DisableIntranetCallsFromApps   True
GuestSharingEnabled            True
pictureExpiryDays              -1
pictureStorageUrl              http://accushare/sites/users/UserPhotos
DisableIntranetCalls           True

I set the pictureExpiryDays to -1 so I could pull down the photos every
time the job was run just for testing.

This is a fresh install of Sharepoint and I'm the only real user who's ever
logged into the sites and I do have a photo in AD.  The other users are my
sharepoint domain accounts SP_Admin and SP_Farm.

**Comment by sbranly** [comment]
Have any ideas for me to try?

**Comment by tseward** [comment]
I need to attempt to repro this issue myself so I can run it through the debugger. What you have looks correct.

**Comment by tseward** [comment]
I was able to repro, and also caught another issue with a similar error (if a domain couldn't be contacted). There is a fix here:

https://github.com/Nauplius/FoundationSync/releases/tag/2.55B

**Comment by tseward** [comment]
Here is a newer solution, please try this instead:

https://github.com/Nauplius/FoundationSync/releases/tag/2.6
