### ISSUE TITLE
Help Docs

### ISSUE THREAD

**Issue by dumbsauce** [Nauplius/FoundationSync#10]
There is minimal documentation to use the solution. Solution installs without error, as does the timer job. Outside of configuring pictures, I see nowhere to work with the solution itself. How do you use this, or where does it show up once installed?

**Comment by tseward** [comment]
Hi, the wiki content is here - https://github.com/Nauplius/FoundationSync/wiki. Anything else you need beyond that?

**Comment by dumbsauce** [comment]
Please forgive my ignorance if I am missing something, but outside of the instructions to install the solution, there's no instructions past that point. Everything looks to have installed fine, timer runs without error, but where can I access the AD information? There's no web parts and nothing to activate in the site collection features. I would like to basically create a page with all the AD information listed (ie phone book), but stuck in a "what now" moment. Any advice?

**Comment by tseward** [comment]
That you would need to create yourself. The AD information is stored in the User Information List, which is an out of the box list. This solution just makes sure those out of the box fields in that list are kept up-to-date.

**Comment by dumbsauce** [comment]
Thanks for the quick reply. That was the first place I checked, but many users are missing. I was reading on the sourceforge page that this solution does not add users that are not already listed in the UIM?

**Comment by tseward** [comment]
That is absolutely correct! Doing so would be a potential change in who has access to the site. I've laid down the foundation to start implementing a central store of user property information. This will be very similar in function to SharePoint Server's User Profile Manager.

**Comment by dumbsauce** [comment]
Ahh.. sorry about this thread then, my expectations were a bit off. Can't do anything until there is a way to sync AD to the UIL first, back to square one.

**Comment by tseward** [comment]
So this project does the AD -> UIL synchronization, but only for users that are there. It sounds like you're looking for a webpart that will generically display AD information about all (or a subset) of users within SharePoint, not attached to SharePoint security. This paid-for solution may be what you're looking for (note I have not used it nor am I endorsing it): http://store.bamboosolutions.com/sharepoint-user-directory-web-part.aspx

**Comment by dumbsauce** [comment]
Thanks again. 
I've also used the same type of solution from Boost Solutions. Worked excellent. Was just trying to find a way to save a grand since they depreciate over the versions, and we're looking to upgrade SharePoint. Ended up scripting a timed sync of AD to SQL, and tied SP into it using EDT and BDC. Good for directory listings.
Cheers.
