### ISSUE TITLE
Timer issue

### ISSUE THREAD

**Issue by topher7612** [Nauplius/FoundationSync#11]
When I first install your plugin, it works right away; however, when I run the plugin manually it does not update the user groups as it did when I first installed it. I have to run the powershell, when I install the plugin, as administrator. Now the plugin was failing in SharePoint right away and I changed the SharePoint TImer service to use Network Service as the log on. Now the job show successful in SharePoint; however, users are not being updated. I do get a event viewer error that has a critical for the SharePoint Foundation Timer 6389. Please help, I need your plugin to work, it is my only hope Obi-Wan Kenobi.

**Comment by tseward** [comment]
Sounds like you have a few things going on.

To address the NetworkService issue, though -- the service (owstimer, that is) must be able to make external calls. I'd strongly recommend you set this to a named Domain User.

Running PowerShell as Admin is to be expected, it is required to interact with SharePoint via PowerShell when using the server-side object model.

**Comment by topher7612** [comment]
As soon as I change it to a domain user and put in the creds, your plugin fails with access denied in the sharepoint job history.

**Comment by tseward** [comment]
Can you provide a stack trace from the ULS that shows the access denied? I'd like to know what the source of that is.

**Comment by topher7612** [comment]
Yeah, I am not that server savvy. Sorry. I actually have no clue how to do a stack trace. I was just hoping I could run the ps1 and get your plugin to work. Like I said it works when I first install it, however after that anytime I run the plugin from the sharepoint job definition I get success, but the permission are not updated.

**Comment by tseward** [comment]
Sure, so what you need to do is grab [ULSViewer](http://www.microsoft.com/en-us/download/details.aspx?id=44020) and run it while you reproduce the issue. You should find the access denied in here, as well.

**Comment by morechud** [comment]
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)), StackTrace:   
 at Microsoft.SharePoint.SPUserCollection.InitUsersCore(Boolean fCustomUsers, String[] strIdentifiers, SPUserCollectionFlags ucf)    
 at Microsoft.SharePoint.SPUserCollection.Undirty()    
 at Microsoft.SharePoint.SPBaseCollection.GetEnumerator()    
 at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()    
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()    
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()    
 at Nauplius.SP.UserSync.SyncJob.Execute(Guid targetInstanceId)    
 at Microsoft.SharePoint.Administration.SPTimerJobInvokeInternal.Invoke(SPJobDefinition jd, Guid targetInstanceId, Boolean isTimerService, Int32& result)    
 at Microsoft.SharePoint.Administration.SPTimerJobInvoke.Invoke(TimerJobExecuteData& data, Int32& result)

**Comment by morechud** [comment]
That is the error message I get in ULSviewer as regards access denied message.

**Comment by tseward** [comment]
Can you give your timer service account (owstimer.exe) Full Control on the User Policy of the Web Application to see if that resolves it?

**Comment by morechud** [comment]
Hello,

I have granted the timer service user access to both domain admin and user
policy for my web application. However, I noticed it the job property that
the web application value is: N/A?

Could this be the problem?

**Comment by morechud** [comment]
I saw it in the farm solutions that this solution is globally deployed.

Please advise on how I can resolve this issue. Many Thanks!!!!!

**Comment by tseward** [comment]
Have you just manually run the timer job?

**Comment by morechud** [comment]
Yes i ran it manually several times but failed. Is there anything else I'm
not doing right?

**Comment by tseward** [comment]
I will have to investigate this more to see what you may be hitting. What user is running your Timer Service (owstimer.exe) and IIS Application Pool(s) that your Web Applications are using?

**Comment by morechud** [comment]
Thanks for your response.

I use admin account for all.

Thanks

**Comment by tseward** [comment]
By 'admin account', do you mean a Domain Administrator? Or just a Domain User who happens to be a Local Administrator on SharePoint?

**Comment by morechud** [comment]
Its an account with Domain Admin membership; also a SharePoint
Administrator.
