### ISSUE TITLE
Settings Cofiguration & Default Settings

### ISSUE THREAD

**Issue by RumisPoint** [Nauplius/FoundationSync#12]
Hello,
I'm getting ready to deploy this solution on my 2010 and 2013 farms.  I a little confused as to whether or not we should be manually configuring the settings.  What are the default settings?  For example, does the solution by default delete the users if not found in AD?  

Also, if I want to limit the timer job to run on a specific server, do I set that after installing the solution but before deploying it?

Thank you,

Rumi

**Comment by tseward** [comment]
By default, boolean settings are all false (including delete users from the UIL if they're not found in AD).  Picture Expiry Days is set to 1, and the Exchange picture size is set to 648x648.

**Comment by RumisPoint** [comment]
Thanks, Trevor.  Once I deploy the solution, how do I configure these settings?  Sorry, I know you have the instructions but can't quite follow them - if I do this via a script or UI?

**Comment by RumisPoint** [comment]
I think I understand.  Ok, so this is what I did to pin the job to a specific server:
    $farm = Get-SPFarm
    $farm.Properties.Add("FoundationSyncPreferredServer", "WFE1")
    $farm.Update()

I then ran the deployment script.  The solution is globally deployed.  But, I can't confirm if the job is pinned to that server or not.  Also, the job does not show up under "scheduled jobs"; however, I do see that it is scheduled daily to run between 12AM and 4AM.

To unpin, I simply run this command, correct?
   $farm = Get-SPFarm
   $farm.Properties.Remove("FoundationSyncPreferredServer")
   $farm.Update()


Further, if I want to change the settings, I first run this?
    $farm = Get-SPFarm
    $obj = $farm.GetObject("7A2A3CFF-383F-42E1-A019-384C8B6FA3E3")

Then, I run the associated setting, for example?
    $obj.DeleteUsers = $true
    $obj.Update()

Finally, by working with the WebApplicationCollection, the timer job will only run against that specific web application?  Can we specify multiple web applications?  And, when I clear the web application, does the timer job then run against all web applications?

Thank you,

**Comment by RumisPoint** [comment]
update:  When I go to scheduled jobs and pick the "Nauplius.SharePoint.FoundationSync" job - I see that it is scheduled at around 1:15AM.  And when I go to see all scheduled job, the reason I don't see it is because the job doesn't have a title so when you are looking at "All" job definitions in the scheduled jobs, the "Job Title" is blank.

**Comment by tseward** [comment]
I'll make sure this is fixed for the next build.

**Comment by RumisPoint** [comment]
Thank you, Trevor.  I just looked at the job and the status indicates "Running" with 0% progress - it's been about 12 hours it is running.

![foundationsync](https://cloud.githubusercontent.com/assets/10838594/10828361/dbe70b8a-7e41-11e5-9767-d933c62789f8.jpg)

**Comment by tseward** [comment]
The job will not show any incremental progress. That said, best bet is to look for the 'Nauplius' category in ULS to see if there is any progress.

**Comment by tseward** [comment]
Please try with the new release, 2.7. If you continue to have an issue, please re-open this issue or start a new one.
