### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by MrBiele** [Nauplius/FoundationSync#13]
Hi,

I`ve got an Error due the installation. 
see attachment.

![ad-import](https://cloud.githubusercontent.com/assets/16952947/12669994/07d2dfe2-c665-11e5-9b78-4a6bded8088e.jpg)

What is the Problem? (It´s a German version from Windows Server 2008 R2/ SharePoint Foundation  Server 2013)
I Hope you can help me, to Handle to Problem.

Many Thanks in Advanced!

**Comment by tseward** [comment]
It looks like the WSP isn't in the same folder as the PowerShell script.

**Comment by MrBiele** [comment]
Hello,

but where can I found the WSP? (it´s not included in zip file!?)
