### ISSUE TITLE
Nauplius.SP.UserSync.AttributePush Error

### ISSUE THREAD

**Issue by danhubgit** [Nauplius/FoundationSync#14]
Hello, i just installed the solution V2.6 on Foundation 2013, but i get an error on execution:
"Exception in method 'execute' in Nauplius.SP.UserSync.AttributePush' (ID 630006b4-a05f-49b1-9bc6-d6f18b500858). object reference was not set to an instance of an object"
What is wrong here?

**Comment by tseward** [comment]
It sounds like the timer job may not be registered. If you go to Central Administration, Monitoring, Review Job Definitions, can you find one named "Nauplius.SharePoint.FoundationSync"?

**Comment by danhubgit** [comment]
Yes, the job is actually there. The error occurs when its startet (manually, scheduled).

**Comment by tseward** [comment]
Is there any additional information from the ULS logs? Can you share the output from:

```
    $farm = Get-SPFarm
    $obj = $farm.GetObject("7A2A3CFF-383F-42E1-A019-384C8B6FA3E3")
```

**Comment by danhubgit** [comment]
Here is what i have so far:

DeleteUsers                 : False
DeleteDisabledUsers         : False
LoggingEx                   : False
WebApplicationCollection    : {SharePoint - 80}
SPSiteCollection            : {}
UseExchange                 : False
PictureStorageUrl           : 
EwsUrl                      : 
PictureExpiryDays           : 1
EwsPictureSize              : 648x648
Name                        : FoundationSyncSettings
TypeName                    : Nauplius.SP.UserSync.FoundationSyncSettings
DisplayName                 : FoundationSyncSettings
Id                          : 7a2a3cff-383f-42e1-a019-384c8b6fa3e3
Status                      : Online
Parent                      : SPFarm Name=SharePoint_Config
Version                     : 177974
Properties                  : {}
Farm                        : SPFarm Name=SharePoint_Config
UpgradedPersistedProperties : {}

02.26.2016 09:31:47.00	OWSTIMER.EXE (0x2A88)	0x3178	SharePoint Foundation	Timer	6398	Critical	The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 630006b4-a05f-49b1-9bc6-d6f18b500858) threw an exception. More information is included below.  Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.	16ee629d-340c-30f6-9778-1aaca680068d

02.26.2016 09:31:47.00	OWSTIMER.EXE (0x2A88)	0x3178	SharePoint Foundation	Timer	72ae	Unexpected	Exception stack trace:    bei Nauplius.SP.UserSync.AttributePush.IsActive(DirectoryEntry de)     bei Nauplius.SP.UserSync.AttributePush.SearchPrincipals(HashSet`1 objPrincipals, SPWebApplication webApplication, SPSite site, Boolean isGroup)     bei Nauplius.SP.UserSync.AttributePush.Execute(Guid targetInstanceId)     bei Microsoft.SharePoint.Administration.SPTimerJobInvokeInternal.Invoke(SPJobDefinition jd, Guid targetInstanceId, Boolean isTimerService, Int32& result)	16ee629d-340c-30f6-9778-1aaca680068d

**Comment by tseward** [comment]
It looks like there is a problem with a specific DirectoryEntry (user account) that wasn't enumerated properly. Do you have a single domain or multiple domains or even multiple forests in place?

**Comment by danhubgit** [comment]
Hi,
we have a single domain. The job is terminated more or less "immediately" after start. Is there something wrong with a user already registered in sharepoint or a AD entry?

**Comment by tseward** [comment]
So what the piece of code is doing is checking if the account is Active in Active Directory or not. What I'm assuming is happening is that an incorrect DirectoryEntry is being passed to that piece of code. I could put in a check, but that seems really unusual. There isn't a way for me to debug the issue without access to the environment where it is occurring, unfortunately.

**Comment by danhubgit** [comment]
The error summary says Duration 0:00:00. It breaks right after start. Does that fit to your assumptions? Seems like something more fundamental to me.

**Comment by tseward** [comment]
Yeah, it should get to that point fairly quickly, especially if the directory is small. It's really going to be tough to tell without hooking up a debugger (Visual Studio) and debugging the code directly :( The only thing I can do is otherwise put a general exception catch around that bit of code, which is a bummer as it doesn't 'solve' the problem.

**Comment by tseward** [comment]
I've added a catch to the IsActive method. That is available from this release (https://onedrive.live.com/redir?resid=CBCE97C71A32BCAE!377585&authkey=!ABrBwfeAW_liQrs&ithint=file%2czip) which if you're interested in testing, let me know how it works out. Given there are no issues, I will post this as a release in the downloads.

**Comment by danhubgit** [comment]
Hello,
works like a Charm and quick!
Thank You!

**Comment by tseward** [comment]
Great, thank you for the feedback. There is one bug in that version where it won't sync groups. I've corrected that in source and will wrap up a release in the next couple of days which will incorporate the group sync fix as well.
