### ISSUE TITLE
Powershell can't find Nauplius.SharePoint.FoundationSync.wsp

### ISSUE THREAD

**Issue by infotect1** [Nauplius/FoundationSync#15]
Hello,
I downloaded the ZIP file and when I run, the script from the Deployment folder, it looks for Nauplius.SharePoint.FoundationSync.wsp and PowerShell fails because the file does not exist in the Deployment folder (or in the ZIP file).  Am I doing something wrong?
Thanks!
-SW

**Comment by tseward** [comment]
Which zip from the Releases page did you download? Looking at the current zip files, both contain the PS1 and WSP file.

**Comment by infotect1** [comment]
Thank you for the prompt response.
Branch says "2013"
I click the "Clone or download" button and select "Download ZIP"
I open the zip and the Deployment folder only has 2 files.  One is .SQL and the other is .PS1

**Comment by tseward** [comment]
That's a copy of the repository (the source code). What you want is the Releases page which contains the compiled code. https://github.com/Nauplius/FoundationSync/releases/tag/2.6

**Comment by infotect1** [comment]
Sorry for being a newb!  lol
Thanks!
