### ISSUE TITLE
Unknown Error after Deployment

### ISSUE THREAD

**Issue by ICCSupport** [Nauplius/FoundationSync#16]
The nauplius/FoundationSync solution was deployed successfully in our Sharepoint 2013 Foundation farm but when I run the solution it fails with an unknown error. Do you know if the solution drops any logs anywhere to identify why it's failing?

**Comment by ICCSupport** [comment]
Here are some of the logs I found:
Unexpected	Unexpected exception attempting to retrieve domain name: BUILTIN.    at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)     at Nauplius.SP.UserSync.AttributePush.GetDomain(String domainName)	540c7e9d-5b4e-1005-ab87-8282c7cdcc0a
05/20/2016 09:36:27.96 	OWSTIMER.EXE (0x20BC)                   	0x15B4	SharePoint Foundation         	Timer                         	6398	Critical	The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID ce2c4755-cafd-466d-b2e9-3f8dab7c91ea) threw an exception. More information is included below.  Unknown error (0x80005000)	540c7e9d-5b4e-1005-ab87-8282c7cdcc0a
05/20/2016 09:36:27.96 	OWSTIMER.EXE (0x20BC)                   	0x15B4	SharePoint Foundation         	Timer                         	72ae	Unexpected	Exception stack trace:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_AdsObject()     at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)     at System.DirectoryServices.DirectorySearcher.FindOne()     at Nauplius.SP.UserSync.AttributePush.SearchPrincipals(HashSet`1 objPrincipals, SPWebApplication webApplication, SPSite site, Boolean isGroup)     at Nauplius.SP.UserSync.AttributePush.Execute(Guid targetInstanceId)     at Microsoft.SharePoint.Administration.SPTimerJobInvokeInternal.Invoke(SPJobDefinition jd, Guid targetInstanceId, Boolean isTimerService, Int32& result)	540c7e9d-5b4e-1005-ab87-8282c7cdcc0a
05/20/2016 09:36:27.98 	OWSTIMER.EXE (0x20BC)                   	0x15B4	SharePoint Foundation         	Monitoring                    	b4ly	High    	Leaving Monitored Scope (Timer Job Nauplius.SharePoint.FoundationSync). Execution Time=11496.7872313381	540c7e9d-5b4e-1005-ab87-8282c7cdcc0a

**Comment by tseward** [comment]
Is your domain name 'BUILTIN'? If not, I'm assuming this is due to accounts that start with 'BUILTIN' (there are a couple of these accounts in Windows, so nothing you're doing wrong and something I need to fix instead :)).

**Comment by ICCSupport** [comment]
Thanks for the quick response. You're correct, our domain name is not 'BUILTIN'.

**Comment by tseward** [comment]
I will be working on a new build this weekend to update that to the hard coded exclusions list.

**Comment by tseward** [comment]
Can you please try with this copy: https://onedrive.live.com/redir?resid=CBCE97C71A32BCAE!377585&authkey=!ABrBwfeAW_liQrs&ithint=file%2czip. Please make sure to use the included PowerShell script to install it (the script will automatically uninstall the previous version properly).

**Comment by tseward** [comment]
I've posted 2.7. If you continue to have a deployment issue with the new release, please re-open this issue or start a new one.

**Comment by ICCSupport** [comment]
Not sure if this is a new issue or it's related to this issue but when the service runs it fails with an Unknown Error (0x80005000).

**Comment by tseward** [comment]
0x80005000 translates to E_ADS_BAD_PATHNAME (An invalid ADSI path name was passed.). Can you give some additional context?

**Comment by tseward** [comment]
Closing as no response.
