### ISSUE TITLE
Couldn't find Nauplius.SharePoint.FoundationSync.wsp

### ISSUE THREAD

**Issue by erdmelone** [Nauplius/FoundationSync#18]
When I start the Script it gives me this error:

Information about this solution can be found at https://github.com/Nauplius/Foun
dationSync/wiki.
License: GPLv2
Release Date: 05/25/1015
Version: 2.6RC
Platform: SharePoint 2013

Install FoundationSync
Do you want to install FoundationSync for SharePoint 2013?
[Y] Y  [N] N  [?] Hilfe (Standard ist "Y"): Y
Starting Installation...
Resolve-Path : Der Pfad
"C:\Users*****\Nauplius.SharePoint.FoundationSync.wsp" kann nicht
gefunden werden, da er nicht vorhanden ist.
In E:\FoundationSync-2013\FoundationSync-2013\DeploymentScript\Nauplius.SharePo
int.FoundationSync.ps1:139 Zeichen:9
- $path = Resolve-Path .\$solutionName
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Users\nkr-ad...ndationSync.w
    sp:String) [Resolve-Path], ItemNotFoundException
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Resol
    vePathCommand

Adding Nauplius.SharePoint.FoundationSync.wsp to SharePoint...

Add-SPSolution : Das Argument kann nicht an den Parameter "LiteralPath"
gebunden werden, da es NULL ist.
In E:\FoundationSync-2013\FoundationSync-2013\DeploymentScript\Nauplius.SharePo
int.FoundationSync.ps1:143 Zeichen:29
- Add-SPSolution -LiteralPath $path | Out-Null
-                             ~~~~~
  - CategoryInfo          : InvalidData: (:) [Add-SPSolution], ParameterBind
    ingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
    icrosoft.SharePoint.PowerShell.SPCmdletAddSolution

Installing Nauplius.SharePoint.FoundationSync.wsp to SharePoint...

Install-SPSolution : Es wurde kein SPSolution-Objekt mit 'Id or Name:
Nauplius.SharePoint.FoundationSync.wsp' gefunden.
In E:\FoundationSync-2013\FoundationSync-2013\DeploymentScript\Nauplius.SharePo
int.FoundationSync.ps1:146 Zeichen:1
- Install-SPSolution -Identity $solutionName -GACDeployment

**Comment by tseward** [comment]
You can do this manually, as well.

```PowerShell
Add-SPSolution C:\path\Nauplius.SharePoint.FoundationSync.wsp
Install-SPSolution nauplius.sharepoint.foundationsync.wsp -GACDeployment
```

**Comment by erdmelone** [comment]
there is no .wsp file when i download your zip :(

**Comment by tseward** [comment]
Which file did you download? This one for 2013 contains it: https://github.com/Nauplius/FoundationSync/releases/download/2.7/Nauplius.SharePoint.FoundationSync-2013-2.7.zip

**Comment by dgomiller** [comment]
I think the releases thing is the problem, got me too because GitHub doesn't work like other download sites.  

https://github.com/Nauplius/FoundationSync/releases

You can find the most recent stuff there, other people.
