### ISSUE TITLE
Sync failed?

### ISSUE THREAD

**Issue by jiriklima** [Nauplius/FoundationSync#19]
Hello
we installed it on our Sharepoint server, but it seems not to do anything. Is there something we do wrong? The status is failed:

Job Title   Nauplius.SharePoint.FoundationSync
Server  ServerName
Web Application  
Content Database  
Status  Failed
Completed   10/5/2016 4:05 PM
Duration (hh:mm:ss) 0:00:29
Error Message   <nativehr>0x80070003</nativehr><nativestack></nativestack>

Can you please help? Thanks :-)

**Comment by tseward** [comment]
0x80070003 translates to directory/path not found, so that's interesting :-) Can you grab the ULS log to see if there is any more information? Can you also provide the output of `Get-SPContentDatabase` (redact any database names/server names as appropriate)? I'm wondering if there is a phantom content database.

**Comment by jiriklima** [comment]
Hello and thanks for reply. I attach the failed job details in TXT.

POS-FS1 is our SQL server, different from Sharepoint machine.
Result of Get-SPContentDatabase is below:

Id               : ac441ea2-c7e1-44f2-be4a-ba70d27cba07
Name             : SharePoint2013_SP2_Content_Production
WebApplication   : SPWebApplication Name=SharePoint - 80
Server           : POS-FS1
CurrentSiteCount : 3

Id               : 868dbf54-9368-4835-b630-11d3d4e37420
Name             : SharePoint2013_SP2_Content_Production_NEW
WebApplication   : SPWebApplication Name=SharePoint - 80
Server           : POS-FS1
CurrentSiteCount : 2

Id               : 3074c62b-98a5-40a2-9653-e4be35744fa9
Name             : WSS_Content_StoragesPromo
WebApplication   : SPWebApplication Name=SharePoint - 80
Server           : POS-FS1
CurrentSiteCount : 1

Id               : 40b19156-bff2-4cfb-a34e-e445e11b8c8e
Name             : SP2013_SP3_Content_Portal
WebApplication   : SPWebApplication Name=SharePoint - 81
Server           : POS-FS1
CurrentSiteCount : 2

[20161005_error-log.txt](https://github.com/Nauplius/FoundationSync/files/519056/20161005_error-log.txt)

**Comment by jiriklima** [comment]
Hello, would you have any advise for me, please?

**Comment by tseward** [comment]
Based on the ULS, it is trying to open a Web that may not exist. What I could suggest for now, since I'm not sure what Web it is based on the log alone, is to dismount and remount your Content Databases in SharePoint.

**Comment by tseward** [comment]
Closing as no response.
