### ISSUE TITLE
Error on group synchronization

### ISSUE THREAD

**Issue by Florent123** [Nauplius/FoundationSync#2]
Hello,

i found this error :

 "The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 92eabe9d-935f-4f24-93f0-afad76bc4f67) threw an exception. More information is included below.  Column 'Account' does not exist. It may have been deleted by another user."

 in Nauplius Logs just after  detection of groups principals.

SharePoint 2010 Foundation
Office Web Apps Server 2010
Search Express 2010
FoundationSync 2.0

Could you help me please ?

Thanks in advance.

Best Regards,
Florent.

**Comment by tseward** [comment]
Is your Web Application Classic or Claims enabled?

**Comment by tseward** [comment]
No further information, closing.

**Comment by tseward** [comment]
Okay, I believe I found the issue and corrected it in this release:

https://github.com/Nauplius/FoundationSync/releases/tag/2.53B
