### ISSUE TITLE
Configure picture update

### ISSUE THREAD

**Issue by dyvyak** [Nauplius/FoundationSync#21]
Hi, is this correct syntax? We don't have pictures stored in AD or Exchange. Pictures are in picture library and user configures url to this picture in profile settings. Everytime timer job runs, it will clear user picture.
$farm = Get-SPFarm
$obj = $farm.GetObject("7A2A3CFF-383F-42E1-A019-384C8B6FA3E3")
$obj.PictureExpiryDays = 2147483647
$obj.Update()

Thanks

**Comment by tseward** [comment]
The solution only picks up from Active Directory or Exchange. It isn't designed to pick up pictures from a file system or Doc Lib in SharePoint.

**Comment by dyvyak** [comment]
Thanks. Is there any way how to tell solution not to touch attribute
picture when i edit it manualy?

**Comment by tseward** [comment]
No, but I will add this as a feature request. This shouldn't be terribly difficult.

**Comment by dyvyak** [comment]
That would be nice. Can i remove this feature from one site collection and
list collections where is it enabled?

**Comment by tseward** [comment]
So you want to disable picture sync from a central location on a single (or multiple) SCs but leave it enabled on others?

**Comment by dyvyak** [comment]
Yes exactly.

**Comment by tseward** [comment]
Ok, I think your first ask is easiest and that is what I'll do first (globally enable/disable) followed by possibly implementing it on a per-SC basis. I can't commit to that last one :)

**Comment by dyvyak** [comment]
what this setting do?
Uri PictureStorageUrl
    A [Uri] object to the absolute path of the UserPhotos picture library

**Comment by dyvyak** [comment]
today i updated to latest version a now sync is not working. i tried to change position attribute in ad but it didn't synchronized to sp. is there anything else that needs to be done?

**Comment by dyvyak** [comment]
There is also feature FoundationSync User Photos Library added after solution deployment. What is this?

**Comment by tseward** [comment]
That feature creates the User Photos library (it really only has to be activated once). Is the attribute in AD named 'position'? If so, what field is it set to synchronize to?

**Comment by dyvyak** [comment]
Attribute in AD is named title. In Sharepoint is named Job title. Would be difficult for you to create option for picture synchronization from picture library based on file name which consist from employee id?
For example $employeeID.jpg . 
Thanks

**Comment by tseward** [comment]
Yeah, that will be the more difficult part of this request. For the title/JobTitle issue, can you see if there are any relevant ULS logs that might help here? The solution does create ULS entries when an update fails.

**Comment by dyvyak** [comment]
Hi, i'll check ULS logs later today.
Did you had any chance to make option "Do not touch attribute picture"?
Thanks

**Comment by tseward** [comment]
I haven't made any changes yet, still in process of rebuilding my lab environment.

**Comment by tseward** [comment]
I'm going to mark this as complete, it will be in the next release. Setting the value of PictureExpiryDays to -1 will prevent the solution from modifying pictures.
