### ISSUE TITLE
Users with filled 'Department' field are not updated

### ISSUE THREAD

**Issue by weirdbiz** [Nauplius/FoundationSync#24]
Hi, 
I have SPF2013 and last version (2.7) of FoundationSync.
Test case: 
1. SPF User's 'Department' field is not empty and the same as in AD (for ex. 'IT'). Change some other field of this user in AD (for ex. Job title).
2. Run sync.
3. User fields are not updated (Last update by System account have not changed).

I did some investigation (_btw, i'm not a dev, so the text below may be like dirty hack_):

- Other user fields combinations may vary, still I have not found its influence on the case.
- Users with empty Department field are syncing correctly.
- If I change Department field in AD, then run sync, the user is synced correctly.
- Found the suspicious part of code in UpdateUser.cs, it looks like from the old revision, before refactoring:
`if ((string)item["Department"] != department)`
`{`
`item["Department"] = department;`
`shouldUpdate = true;`
`}`
- Found the variable `shouldUpdate`, which is sometimes going to be '_false_' at the end of '_for_' loop, so `item.Update();` is never called, so user is not updated, even if array contains some updated fields.

I tried to fix this and came to this changes:

- Remove above block of code.
- Define `shouldUpdate` variable as `private static bool shouldUpdate = false;` outside of method '_User_' (keep `shouldUpdate = false;` in the loop).
- Call `TryUpdateValue();` without assigning to `shouldUpdate` variable everywhere in '_UpdateUser.cs_'.
- Add `shouldUpdate = true;` in the above method before `return true;`, if some field is updated, we have to update user anyway.

I did some tests, it appears that bug is gone. Other things work fine.

**Comment by tseward** [comment]
Thanks! Can you submit with a pull request so I can get that in the main branch?

**Comment by tseward** [comment]
Actually, suggestion implemented in commit 05a97ab9fce820eb7910dc6d8e592edaeaf9fd3f. Also updated this for groups, since the same bug would be there as well.

**Comment by tseward** [comment]
Fix applied to the published 2.71 release.
