### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by anandsarath** [Nauplius/FoundationSync#26]
![capture](https://cloud.githubusercontent.com/assets/26873829/24953556/5b973b4e-1f99-11e7-9b73-be035364de25.PNG)

Getting the following error while running the PS1 file, also cant find the WSP file anywhere.

**Comment by tseward** [comment]
Please download the release zip file from here: https://github.com/Nauplius/FoundationSync/releases. This package contains the PowerShell and WSP, which should reside in the same directory.
