### ISSUE TITLE
No Scheduled jobs

### ISSUE THREAD

**Issue by RumisPoint** [Nauplius/FoundationSync#28]
Hello:

I just deploy FoundationSync on my SP Foundation 2013 farm.  When I look at the timer job, I noticed there is nothing scheduled.  Should I see a schedule for this?

Also, what are the default settings in the settings objects?

Thank you much!

![timer schedule job](https://user-images.githubusercontent.com/10838594/29368780-557c27f8-8266-11e7-9197-645e1e378e55.jpg)

**Comment by tseward** [comment]
Hi, it should certainly have a schedule. It is set to start between midnight and 4 AM daily, by default. As for the settings object, the defaults are as follows.

```PowerShell
DeleteUsers                 : False
DeleteDisabledUsers         : False
LoggingEx                   : False
WebApplicationCollection    : {}
SPSiteCollection            : {}
UseExchange                 : False
PictureStorageUrl           : 
EwsUrl                      :
PictureExpiryDays           : 1
EwsPictureSize              : 648x648
AdditionalUserAttributes    : {}
ConnectionString            :
Name                        : FoundationSyncSettings
TypeName                    : Nauplius.SP.UserSync.FoundationSyncSettings
DisplayName                 : FoundationSyncSettings
Id                          : 7a2a3cff-383f-42e1-a019-384c8b6fa3e3
Status                      : Online
Parent                      : SPFarm Name=ConfigDbName
Version                     : 1030078
Properties                  : {}
Farm                        : SPFarm Name=ConfigDbName
UpgradedPersistedProperties : {}
```

**Comment by RumisPoint** [comment]
Thank you.  I see that if I look by Job Definition - I do see the schedule and the Job name is different: "Nauplius.SharePoint.FoundationSync".  But, if I filter by Service - it has a different name and this does not have a schedule:  "Nauplius.SP.UserSync.FoundationSync".  Are these different jobs?

![timer job definition](https://user-images.githubusercontent.com/10838594/29371940-610e6de8-826f-11e7-8ba8-40760e13de5e.jpg)
![timer schedule job](https://user-images.githubusercontent.com/10838594/29371946-6562338e-826f-11e7-96d7-4dec184a9e3a.jpg)

**Comment by tseward** [comment]
That service name isn't correct. I would suggest removing/reinstalling. Will release an update soon.
