### ISSUE TITLE
How to use user data ?

### ISSUE THREAD

**Issue by cubs222** [Nauplius/FoundationSync#29]
Hi

It's not issue rather my lack of knowledge, but how can I use this imported user data ?
I see that job is running and working, I see users data updated on UIL (User information list), but how can I for example search for those users (or use this in any differen place than UIL) ?

Regards,

**Comment by tseward** [comment]
The data isn't stored centrally in the farm. You may be able to search the data by specifying the path to the list itself on the site, but this would be on a site collection by site collection basis.
