### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nunonaos** [Nauplius/FoundationSync#31]
Hello, I have sharepoint foundation in a cloud server (so, not in my domain).
Is it possible to make this work for me?

Thanks

**Comment by tseward** [comment]
It depends on your configuration. Are you using Windows authentication, or SAML? This solution only works with Windows auth.

**Comment by nunonaos** [comment]
I don't have access to the site administration, only to site settings, but I believe this login type is windows authentication. (see attached image)
The server admin installed the package but I'm thinking i need to give it instructions on where to retrieve the AD users, right?
![untitled](https://user-images.githubusercontent.com/15946573/35345523-c59c2ea8-0127-11e8-8bcd-f7a4c2f7e8ea.png)

**Comment by tseward** [comment]
This is a farm solution, so you would need full control over the SharePoint server. But if it is indeed using Windows Authentication, then yes it should work provided the solution is deployed.

**Comment by nunonaos** [comment]
ok thanks, first i have to understand how they have windows authentication in a cloud server... that's a bit strange to me because then the users will be from their domain, not mine...
