### ISSUE TITLE
Account aren't synced though photos are

### ISSUE THREAD

**Issue by alextopol** [Nauplius/FoundationSync#33]
Hi, UserPhotos lib IS populated with a user picture, but user list isn't updated, no errors, execution time is 0.

**Comment by tseward** [comment]
Can you set your ULS to VerboseEx (`Set-SPLogLevel -TraceSeverity VerboseEx`), re-run the timer job. You'll want to run `Clear-SPLogLevel` once the job has finished.

Are you using a Domain User for your Farm Admin account or NETWORK SERVICE/local user?

**Comment by musikfipsi2003** [comment]
Hi, same problem here. User pictures are successfully stored in UserPhotos library but profiles are not updated with picture url. Seams like other attributes are updated without any problems...

**Comment by tseward** [comment]
I left out the method that performs the update on the Picture field in the UIL. Fixed in release 2.73 available on the Releases tab.
