### ISSUE TITLE
Unable to update accounts from a domain trust

### ISSUE THREAD

**Issue by tseward** [Nauplius/FoundationSync#5]
Trust type: Root, Transitive

Users are not being updated from trusted domains.

**Comment by anehodges** [comment]
Is there an ETA for a fix for this issue?

**Comment by tseward** [comment]
I just uploaded a new release. Try it out and let me know if it works for you.

**Comment by anehodges** [comment]
Now I get…
[cid:image001.png@01D07B55.F71DB420]


Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
Hi, the image did not come through.

**Comment by anehodges** [comment]
Error message was domain does not exist or cannot be contacted…

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
For your users on the trusted domain, does the NetBIOS name match the FQDN (e.g. CONTOSO and Contoso.com)?

**Comment by anehodges** [comment]
The users are in a different domain than the Sharepoint server

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by anehodges** [comment]
The name of the server and the site name are not the same – is that what you’re looking for?  There are also several sites on the server….

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
No, what I'm looking for is the NetBIOS name versus FQDN of the Active Directory Domain name these users are from.

**Comment by anehodges** [comment]
FQDN is 1234.nv.us and Netbios is 1234…  1234=AD NAME



Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
Great, thank you. Do you get correct results while running this from the SharePoint server: nltest /dsgetdc:1234? See example below:

    nltest /dsgetdc:contoso
           DC: \\WIN-JTWSYH0DVDI (this is the domain controller's name for CONTOSO)
      Address: \\<IP_or_FQDN>
     Dom Guid: 63606f48-6ff8-491e-9d47-2361bbfbb795
     Dom Name: CONTOSO
  Forest Name: contoso.local
 Dc Site Name: Default-First-Site-Name
Our Site Name: Default-First-Site-Name

**Comment by anehodges** [comment]
Yes – everything is correct.  I even ran it for both the user and resource domains and it returns correct information for both.


Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
And because I don't think I asked, this is a two-way Forest trust, correct?

**Comment by anehodges** [comment]
The two domains are in the same forest.  The domain the server is in is a child domain of the ‘user’ domain.

I was just thinking though…  As the ‘user’ domain is a domain that contains ALL state users (so MANY more than just ‘our’ users) there are several other Domain Trusts for other agencies that we do not care about or use for sharepoint – could these other domains be the issue?

Also – we use to have a 3rd domain that ‘had’ access, but the domain no longer has users in it – could it be this one?

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
The solution will look at users who exist within SharePoint [User Information List], even if they're from defunct domains or domains the SharePoint servers do not have access to (as well as one-way trusted domains, which this solution does not support). What would help me is if you created a user in that trusted domain, or modified a user from that trusted domain which have been been added to SharePoint, and change the value of 'Department' or 'Job Title', then re-run the solution. If it picks up the changes from the trusted domain, then we can consider this resolved.

**Comment by anehodges** [comment]
Thank you – should this work for ALL site collections on the server?  It appears to have updated for the main site on port 80 but not the second site on a different port.

Really appreciate your help.

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.

**Comment by tseward** [comment]
Yes, it is a farm-wide solution and will work against all Site Collections on the farm (with the exception of Central Administration), although the ability to make exclusions is available.

What I would suggest is turning on Verbose logging in Central Admin -> Monitoring for the category 'Nauplius' and then run the timer job. It should give you a better idea of why it may not be updating.

**Comment by tseward** [comment]
Anedrea, are you able to provide additional details for the second site that did not update properly? Or can I consider this issue as closed?

**Comment by anehodges** [comment]
You can consider the issue closed at this time.

Anedrea Hodges, IT Manager I
Field and Technical Services
Office of Informatics & Technology
Nevada Division of Public & Behavioral Health
Direct: 702.486.3929
Office Manager: 775.684.5924

PBH Help Desk
Phone:  702.486.3699 or 775.684.5906
Email:  healthsupport@health.nv.gov<mailto:healthsupport@health.nv.gov>
Self-Service: http://dhhsisd101.dhhs-ad.state.nv.us/TrackItWebHD/selfservice/login


This message and accompanying documents are covered by the electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, may be covered by the Health Insurance Portability and Accountability Act (HIPAA) of 1996 and may contain confidential information or Protected Health Information intended for the specified individual(s) only. If you are not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that any review, dissemination, copying, or the taking of any action based on the contents of this information is strictly prohibited. Violations may result in administrative, civil, or criminal penalties. If you have received this communication in error, please notify sender immediately by e-mail, and delete the message.
