### ISSUE TITLE
Feature Request: Add more fields

### ISSUE THREAD

**Issue by andy68man** [Nauplius/FoundationSync#6]
Hello,

I've been using FoundationSync for Sharepoint 2013 - thanks for writing it! It's been working well (you even released a fix for me that sorted my install issue), but I've had a few requests from users for some additional AD fields to be added.

I've followed a guide I found here: http://www.macaalay.com/2014/03/27/synchronize-active-directory-information-with-sharepoint-foundation-2013-user-profiles/

This has let me add additional fields to the list (Primary Phone, Office, Address), but now I need to get them synced from AD. Would it be possible for me to mod the code to be able to do this? Or is this a feature you could add in? Any tips on where to start?

Thanks,

Andy

**Comment by tseward** [comment]
Yes, you can modify the code, changing UpdateUilUser (Push.cs) to accommodate your additional properties. If you look at line 353 and the couple after it, just duplicate that for each property you want to add.

One thing I may consider is adding a sort of universal way to do this via the FoundationSyncSettings object. It should be possible t make a collection of key:value pairs (that is, FieldName:activeDirectoryProperty) and simply loop through that within UpdateUilUser.

**Comment by andy68man** [comment]
Ah that's great! Presumably I need to install Visual Studio Express 2012 onto the sharepoint server, download the source code, make the changes and then compile to a new wsp and re-install...?

Thanks,

Andy

**Comment by tseward** [comment]
You will need Visual Studio 2013. Yes, it must be installed on a SharePoint server, but you should never install VS on your production server.

**Comment by andy68man** [comment]
Hello,

I created a separate SharePoint server, installed Visual Studio community edition, and was able to make all the changes to the code and create a new wsp file. It didn't work at first as I had the SharePoint fields with the wrong name, but I was able to inspect the elements in IE on the edit user form to find their proper names, update the code, and it's working great.

Thanks for all your help and tips, really appreciate how quickly you've responded to both mine and other users queries.

Regards,

Andy

**Comment by tseward** [comment]
Thanks, I'm glad it worked out for you! I'll be adding a separate enhancement for this functionality.

**Comment by mattyjpeterson** [comment]
I created a temporary SP2013 server and I went through the process of adding two more fields in Push.cs, then deploying the new solution. I had to specify a different Site URL (http://localhost) than my production site, in order for VS to accept the Site URL value. I moved the newly built .wsp file to my production server and installed FoundationSync again.

I keep getting a "Column 'WorkNumber' does not exist" when I run the newly created job. Because of the error, the job fails and my User data doesn't update the User Information List.

I then reinstalled the original program from your site and modified a field (Mobile phone number) and it ran successfully.

I'm not sure what I am doing wrong, as I was certain it would work. Any suggestions?

**Comment by tseward** [comment]
Was WorkNumber the internal column name? If you look at the List (UIL) in PowerShell, Do you see your column?

**Comment by mattyjpeterson** [comment]
Thanks for asking me to go back again and check. I found the internal field name for "Business Phone" is "WorkPhone", not "WorkNumber". I updated the code, rebuilt the solution, reinstalled FoundationSync again. Now the event viewer shows "Column 'WorkPhone' does not exist".

I'm not sure how to verify the Column:InternalFieldName relationship in Powershell. I did verify that "Business Phone" uses "WorkPhone" as the internal field name by hovering over Business Phone in Site Settings>Site Columns. The link at the bottom of IE shows "Field=WorkPhone" in the URL.

**Comment by tseward** [comment]
You can find it this way:

```PowerShell
$site = Get-SPSite http://siteUrl
$site.RootWeb.SiteUserInfoList.Fields | Select Title,InternalName
```

**Comment by mattyjpeterson** [comment]
Thank you. I've been looking for that info for the past hour.

Unfortunately, it shows the same result as my previous post. Business Phone = WorkPhone

Here's my addition to your code:
```c#
item["WorkPhone"] = (directoryEntry.Properties["telephoneNumber"].Value == null)
                          ? string.Empty
                          : directoryEntry.Properties["telephoneNumber"].Value.ToString();
```
I verified that telephoneNumber is the correct attribute in Active Directory.

**Comment by mattyjpeterson** [comment]
Is it possible that this issue stems from what I enter in the "Site URL" field in the Properties Window when compiling the code using Visual Studio 2013? 

It throws an error when I try to put in the URL of my production Sharepoint site.

**Comment by tseward** [comment]
This is a general problem with VS. What you can do is add a hosts file entry for 127.0.0.1 hostname for your site.

**Comment by mattyjpeterson** [comment]
I did find this during my research. I'm able to build the solution with the correct siteURL in the properties now. However, I can't get past the same error message. The entire message in the Event Viewer is:
```
The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 0de4cd2b-7714-4f80-8c53-9a6d0840f5b8) threw an exception. More information is included below.

Column 'WorkPhone' does not exist. It may have been deleted by another user.
```
There is most likely something I'm missing. Anything else you can think of? I'm stumped at this point.

**Comment by andy68man** [comment]
Hey Matty,

I had this issue - the fields in sharepoint sometime bear no relation to what you think they should be called. To find them, login to sharepoint and click on a user, and then click "Edit Item". In the form, click in the text box next to the field name you're looking for, and then right click and inspect element.

You'll see a load of rubbish in the input name, but in green writing above, you'll see the FieldName and the FieldInternalName. From memory, you have to use the FieldInternalName or you'll get the error you have above. I added fields one at a time and recompiled so I could make sure it worked correctly.

![image](https://cloud.githubusercontent.com/assets/10629727/8102744/71cc784c-101a-11e5-8bc4-62397fcc8680.png)

Hope that helps,

Andy

**Comment by andy68man** [comment]
Hello,

I was getting a different issue where it only seems to be syncing half of the users:
The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID e765beb5-fead-412c-bd25-d003b1adad95) threw an exception. More information is included below.

The specified domain does not exist or cannot be contacted.

So I thought I would download the latest version, add my code and upgrade. I have done, and I'm now getting exactly the same error as matty:
The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 24a61d8f-9b31-453c-b568-7784d56c546a) threw an exception. More information is included below.

Column 'PrimaryNumber' does not exist. It may have been deleted by another user.

I think the latest version may have broken the custom fields we added...? If I go back to the version I had in May, it works fine, but I get the domain error.

Thanks,

Andy

**Comment by andy68man** [comment]
Just an update - I made my way back to version 2.53B, and I get a slightly different error but it seems to process more of my users:

The Execute method of job definition Nauplius.SP.UserSync.AttributePush (ID 4af29544-3be1-4cbe-813d-a22d7dc5c4a8) threw an exception. More information is included below.  Object reference not set to an instance of an object.	564e0f9d-40b1-00e8-2382-7aabc06b43f0

I think it may not like one of my users or some of the info from AD...? Any way to troubleshoot it a bit further...?

**Comment by tseward** [comment]
Since you have Visual Studio, can you debug the issue with the current version? Have you made sure all Site Collections in the farm have this new UIL field? Or if not, are doing a form of try/catch in the code when attempting to update the field?

**Comment by andy68man** [comment]
I don't really have the skills to troubleshoot it properly unfortunately, but I added the try/catch around the custom fields and the error has gone, but it seems to get stuck in the list somewhere as the first few users are updated, but the later ones aren't.

I can see that you've added logging in, where can I check the logs to see which accounts have been updated? I'm wondering if there is an illegal character in the AD info somewhere.

Thanks,

Andy

**Comment by tseward** [comment]
The logging doesn't look at individual users. That would require some more work, e.g. comparing the LDAP value to the Site Collection field value for the user.

**Comment by andy68man** [comment]
Hello,

After closer inspection, I think that the try{} fixed it! The AD accounts
that weren't updating were disabled, so of course, the info wasn't updated.
I've written a nightly powershell to remove any accounts that are disabled
from SharePoint, and add any new ones just before the sync runs.

Matty, you just need to amend the code to add "try{" before your custom
fields, and  "}catch {}" at the end. That then worked fine for me.

Thanks,

Andy

**Comment by mattyjpeterson** [comment]
Regarding Andy's first comment to me, I had the correct field names. Thanks for the alternate way to view these. Trevor's suggestion to use PowerShell to view these was also a great way to compare the field names.

Andy - Where exactly should I insert the Try/Catch code for my custom fields? Here?:
```c#
try{
item["WorkFax"] = (directoryEntry.Properties["facsimileTelephoneNumber"].Value == null)
                    ? string.Empty
                    : directoryEntry.Properties["facsimileTelephoneNumber"].Value.ToString();
}catch{}
```

**Comment by mattyjpeterson** [comment]
Andy's suggestion fixed the issue! I amended my custom field code in Push.cs as follows
```c#
try
{
   item["WorkPhone"] = (directoryEntry.Properties["telephoneNumber"].Value == null)
                         ? string.Empty
                         : directoryEntry.Properties["telephoneNumber"].Value.ToString();

   item["WorkFax"] = (directoryEntry.Properties["facsimileTelephoneNumber"].Value == null)
                         ? string.Empty
                         : directoryEntry.Properties["facsimileTelephoneNumber"].Value.ToString();
}
catch { }
```
I then rebuilt the .wsp file and reinstalled FoundationSync to apply the new code. FoundationSync is now updating the Business Phone and Fax Number fields beautifully.

I appreciate the help Andy and Trevor. Thanks for building this awesome tool Trevor. I'm excited to see how it develops in the future.
